stocks:
  name: test
  load:
      stock1:  
        id: 1
        name: Stock1
        currentPrice: 10
        lastUpdate: 0
      stock2: 
        id: 2
        name: Stock2
        currentPrice: 20
        lastUpdate: 0
      stock3: 
        id: 3
        name: Stock3
        currentPrice: 30
        lastUpdate: 0