version: "3"
services:
  redis:
    image: "stocksredis:latest"
    build:
      context: ./redis
    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"
    networks:
      - mynet
  springboot:
    image: "stocksspringboot:latest"
    build:
      context: ./stocksservice
      args:
        jarFile: "stocks-service-0.0.1-SNAPSHOT.jar"
    volumes:
      - $PWD:/code
    ports:
      - "127.0.0.1:${SERVICE_PORT:-8080}:8080"
    networks:
      - mynet
    depends_on:
      - redis
networks:
  mynet: