version: "3"
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "127.0.0.1:${MONGODB_PORT:-27017}:27017"
    networks:
      - mynet
  springboot:
    image: "springboot:latest"
    build:
      context: .
      args:
        jarFile: "amazing-test-service-1.0-SNAPSHOT.jar"
    volumes:
      - $PWD:/code
    ports:
      - "127.0.0.1:${SERVICE_PORT:-8080}:8080"
    networks:
      - mynet
    depends_on:
      - mongodb
networks:
  mynet: