version: "3"
services:
  redis:
    image: "jamerson/stocksredis:latest"
    build:
      context: ./redis
    ports:
      - "6379"
    networks:
      - mynet
  springboot:
    environment:
      - IN_MEM_PERSIST
      - SPRING_PROFILES_ACTIVE  
      - SPRING_REDIS_HOST
    image: "jamerson/stocksspringboot:latest"
    build:
      context: ./stocksservice
      args:
        jarFile: "stocks-service-0.0.1-SNAPSHOT.jar"
    volumes:
      - $PWD:/code
    ports:
      - "127.0.0.1:${SERVICE_PORT:-8080}:8080"
    networks:
      - mynet
    depends_on:
      - redis
networks:
  mynet: